### ISSUE TITLE
Make use of http.ServeContent

### ISSUE THREAD

**Issue by jpillora** [bouk/staticfiles#1]
Sorry if I missed something, though ServeHTTP might be improved with https://golang.org/pkg/net/http/#ServeContent (handles mime types based on filename, range requests, last modified caching)

**Comment by bouk** [comment]
Hi! It's not possible to use ServeContent with compressed data, because you can't seek a GZIP reader. This would mean that the server needs to decompress everything on load, leading to more memory usage and such, which is why I decided against it.

I implemented mime types and modtime/etag caching myself, so it's just range requests that won't work.

Thanks for the suggestion!
